### ISSUE TITLE
Teleport to my actual location randomly occurs

### ISSUE THREAD

**Issue by alessandrotesoro** [iam4x/pokemongo-webspoof#121] opened 2016-07-21 13:23 UTC
Hi there,

Thanks for this great app, I've just noticed a glitch and I'm not sure what's the cause or how to avoid it. 

When I set autopilot the player starts moving correctly however every now and then it teleports itself to my "real" location for a second (maybe even less) and then teleports itself again to the position it had just left.

Any idea what's causing this and how to fix it?

**Comment by Lumerias** [comment] 2016-07-21 14:15
I'm also having an issue where it will randomly teleport back to one of the last locations I started the app on. I'll be battling in a gym and no matter where I started the app (real location or spoof location), I'll jump back to that original location until I hit the arrow and then will jump back to where I actually am. Not sure what is causing this.

**Comment by AbelIngrand** [comment] 2016-07-21 15:04
Could you tell if the jump happens only in Pokemon Go or also on the app's map ?

**Comment by MattFlood7** [comment] 2016-07-21 15:06
I am also having this issue. It appears to only happen in Pokemon Go and not in the Webspoof App.

**Comment by AbelIngrand** [comment] 2016-07-21 15:17
If it only happens in the game and not in the map, I think it comes from the same issue as #125 (see my comment here https://github.com/iam4x/pokemongo-webspoof/issues/125#issuecomment-234285558)

Do Xcode give an error message or gives any log in the console?

**Comment by MattFlood7** [comment] 2016-07-21 15:19
I do not think so. When I go on lunch in a little I'll see if I can reproduce and put any errors/logging I find on here.

**Comment by alessandrotesoro** [comment] 2016-07-21 15:25
I've been using the app for 2 hours now and it hasn't happened again. Could it be caused by other apps on the phone that use locations? Like "find my phone" ?

**Comment by grinsekatze003** [comment] 2016-07-21 15:26
Could it be that Pokemon Go takes so much resources so that iOS kills the webspoof app running in background?

**Comment by MattFlood7** [comment] 2016-07-21 15:38
I know that iOS does actually operate in that manner. It's a very rare situation from my experience. I am actually dealing with a situation like this at work right now.

**Comment by AbelIngrand** [comment] 2016-07-21 15:42
Also look if the iPhone still appears in Xcode and if it still says the app is running on your iPhone.

**Comment by AbelIngrand** [comment] 2016-07-21 15:43
I actually patched this problem of the app quitting when not enough memory was availed. Try updating to the latest version and tell me if it still happens

**Comment by iam4x** [comment] 2016-07-21 15:44
@AbelIngrand In fact I'm testing your fix that I merged on master. Guess what: 

![screen shot 2016-07-21 at 17 43 47](https://cloud.githubusercontent.com/assets/893837/17029225/b8af8f02-4f6a-11e6-8f9f-f70d0e7a525b.png)

It won't be possible to keep it running in background when device has no more memory, it's running on an iPhone5. When I restart my iPhone it stays much longer open 👍

**Comment by djadstar** [comment] 2016-07-21 15:49
I had the same issue, also found it happened when you debug and refresh background data. Only happens very rarely.

**Comment by AbelIngrand** [comment] 2016-07-21 17:19
Strange, the blank audio should keep the app running. Maybe I missed something, I'll look into it.

**Comment by ferazambuja** [comment] 2016-07-21 17:22
It happens for me when I don't have the app window active selected.
Just happen now while typing this message. It takes a few minutes...

**Comment by grinsekatze003** [comment] 2016-07-21 19:14
@ferazambuja Which window do you mean? Xcode, the Mac App or the blank iOS App?

**Comment by ferazambuja** [comment] 2016-07-21 19:55
The pockemongo-webspoof.app on the mac.
If I'm idle for a period on the phone, I just switch back to the "white screen" app on the phone.

**Comment by iam4x** [comment] 2016-07-21 20:05
I'll tag this as wontfix, since we tried multiple solution. I think we should add a note to re-focus app every ~10-15 minutes 👍

**Comment by jhoye88** [comment] 2016-07-21 20:30
@iam4x when you say re-focus the app, i assume you mean the one thats running on the iOS device?

**Comment by iam4x** [comment] 2016-07-21 20:33
@jhoye88 Yes

**Comment by Venorcis** [comment] 2016-07-22 07:30
@iam4x 1.1.1 seems to crash way more often than 1.1.0 for me unfortunately

**Comment by nikhdpro** [comment] 2016-07-22 10:13
Hey @iam4x and @AbelIngrand I've fixed this issue. Unfortunately I didn't really download the dev version of your code. 

After doing some debugging using a different (audible) mp3 file, I realised that although the file path was found, the mp3 itself never started to play. 

The issue in the code is essentially that the silent mp3 was not really playing in the background because AVAudioPlayer had not been sent an alloc and the delegate for the AVAudioPlayer instance was not set. Also, for some reason, to get backgrounding, setting the AVAudioPlayer instance as a property of the .m file is recommended (Ask Apple why lol).

This is what my ViewController.m file looks like after these changes:

```
#import "ViewController.h"
#import "AVFoundation/AVFoundation.h"
#import "AudioToolbox/AudioToolbox.h"


@interface ViewController () <AVAudioPlayerDelegate> {
    
}
//Property for AVAudioPlayer to play a silent file in a infinite loop
@property(nonatomic,strong)AVAudioPlayer *backgroundAudioPlayer;
@end

@implementation ViewController

- (void)viewDidLoad {
    [super viewDidLoad];
    
    NSURL *url = [NSURL fileURLWithPath:[[NSBundle mainBundle] pathForResource:@"silent" ofType:@"mp3"]];
    self.backgroundAudioPlayer=[[AVAudioPlayer alloc] initWithContentsOfURL:url error:nil];
    self.backgroundAudioPlayer.numberOfLoops=-1;
    
    [[AVAudioSession sharedInstance] setCategory:AVAudioSessionCategoryPlayback withOptions:AVAudioSessionCategoryOptionInterruptSpokenAudioAndMixWithOthers error:nil]; //Allows the silent audio to play along side iTunes
    [[UIApplication sharedApplication] beginReceivingRemoteControlEvents];
    [[AVAudioSession sharedInstance] setActive:YES withOptions:AVAudioSessionSetActiveOptionNotifyOthersOnDeactivation error:nil];
    
    self.backgroundAudioPlayer.delegate = self;
    [self.backgroundAudioPlayer play];
    

    
}


- (void)didReceiveMemoryWarning {
    [super didReceiveMemoryWarning];
    // Dispose of any resources that can be recreated.
}

@end
```

Sorry I am currently too busy to actually clone the dev version on github and create a pull request.
I realise you have added IBActions to open Pokemon Go from the app which is awesome and not part of the version of the code I updated.

Hope this works for you. I have been able to keep the app running in the background indefinitely this way with no issues. It might be a good idea to include a warning in the app loading screen reminding people to quit the app after they are done spoofing to prevent unnecessary battery drain.

**Comment by AbelIngrand** [comment] 2016-07-22 10:41
My bad for the wrong implementation. It's been fixed in #156 using the same work around you proposed. Thanks for your help !

**Closed** 2016-07-22 10:41 UTC
Labels: bug, help wanted, wontfix

**Comment by iam4x** [comment] 2016-07-22 10:45
Thank's for the feedback @nikhdpro 💃

**Comment by nikhdpro** [comment] 2016-07-22 10:49
No worries guys! Happy to help, glad that the project feels real stable at this early stage haha!

**Comment by Takage** [comment] 2016-07-24 19:18
Any word when 1.1.2 will be out?
