### ISSUE TITLE
Webspoof app stopped running after a while, especially frequently when checking gyms

### ISSUE THREAD

**Issue by wxrdn** [iam4x/pokemongo-webspoof#31] opened 2016-07-18 08:11 UTC
I have noticed while navigating my city through this webspoof app, sometimes it will just stop running and Xcode status will say something like "Finished running webspoof on XXX's iphone". This happens frequently when I visit gyms and then I will be teleported back to where my real location is. Do you know why this happens and if possible, a fix? Many thanks!

**Comment by iam4x** [comment] 2016-07-18 08:17
If you open Xcode debugger you will see that the app stops because of memory warning, I suspect Pokémon Go to use too much resources.

When it happens to be to much frequent reboot your iOS device it helps. I have no fixes for the moment :(

**Comment by wxrdn** [comment] 2016-07-18 08:35
thanks for the quick reply! If I simply kill and restart the Pokemon app (instead of reboot my phone), would it release the memory/resource it held?

**Comment by james-145** [comment] 2016-07-18 10:33
Further research shows that this is a duplicate of #12 and @iam4x is correct, when you enter an area of high activity, pokemon uses lots of resources and background processes are killed, I've tried a few other solutions (including switching back every minute) but not found a solution yet

**Comment by iam4x** [comment] 2016-07-18 11:02
@james-145 Yes you need special privileges from apple to keep app running, that sucks I have no idea how to change that. Going to talk to iOS dev at my workplace.
 
Let's continue discussion in #12 👍

**Closed by iam4x** 2016-07-18 11:02 UTC
Labels: help wanted, wontfix

**Comment by iam4x** [comment] 2016-07-18 11:22
Will be fixed in next release 🎉
