### ISSUE TITLE
Some issues in Xcode

### ISSUE THREAD

**Issue by Th3RedEye** [iam4x/pokemongo-webspoof#119] opened 2016-07-21 08:06 UTC
Hi, got some issues in Xcode.
1. I can't rename the Bundle Identifier 
2. Then when I click on the "fix issues" button, the application asks me for a Developper Apple Account.
3. When I'm trying to build & run the application on the connected iPhone, my iPhone appears in the "Ineligible Devices" category.

I'm running Xcode 6.4 (6E35b) on a MacBook Pro Yosemite 10.10.5 and my iPhone 6S+ is in 9.3.3
Thanks for your help

**Comment by realphanta** [comment] 2016-07-21 08:12
Does it really ask for a developer account? I guess any iCloud account works fine. At least it did for me.

**Comment by Th3RedEye** [comment] 2016-07-21 08:24
As you can see in the pictures below.
![capture d ecran 2016-07-21 a 10 23 23](https://cloud.githubusercontent.com/assets/20574294/17016001/429ec284-4f2d-11e6-98f6-8ad3938007af.png)
![capture d ecran 2016-07-21 a 10 23 04](https://cloud.githubusercontent.com/assets/20574294/17016000/429ead58-4f2d-11e6-8b2a-4d009b5e4784.png)
![capture d ecran 2016-07-21 a 10 22 42](https://cloud.githubusercontent.com/assets/20574294/17016002/42a0be7c-4f2d-11e6-8f4d-1c24f21cfb4c.png)

**Comment by realphanta** [comment] 2016-07-21 08:31
And I guess you tried your iCloud account!? I remember seeing the developer account message, not sure what I did to resolve it.
In the screenshot you did not change the Bundle Identifier, though. Maybe this is part of the problem?

**Comment by djadstar** [comment] 2016-07-21 10:34
I fixed this by adding a normal cloud account. Then went to general>devices and trusted the account

**Comment by d3viant0ne** [comment] 2016-07-21 15:34
@Th3RedEye 
You will also run into an issue with the bundle identifier in some cases.

- Right click and "show package contents"
- Navigate to the xcode project under resources/app
- Open the xcode project
- Modify the bundle name `com.<yourDevName>.pokemon-webspoof` where <yourDevName> correlates to the team settings defined.
- Set your `team`
- Close xcode project

Now every time you open the app it will launch with your dev settings not the published ones.

**Comment by iam4x** [comment] 2016-07-21 20:04
Duplicate of #16

**Closed by iam4x** 2016-07-21 20:04 UTC

**Comment by Th3RedEye** [comment] 2016-07-22 12:28
As you can see in the second screenshot, I can't edit the bundle name, it's greyed out

**Comment by michaelowens** [comment] 2016-07-22 13:17
Same issue here, bundle name is also greyed out and won't let me change it.
