### ISSUE TITLE
Lat and Ing input text boxes

### ISSUE THREAD

**Issue by Juank1995** [iam4x/pokemongo-webspoof#142] opened 2016-07-21 20:14 UTC
It is very difficult to type in some specific coordinates. In both text boxes, if you click inside and want to move in between the numbers by pressing the left or right arrow, the program moves your position instead of moving in the text box. Also, if you erase  the point in the text box you can't type it back in

**Comment by iam4x** [comment] 2016-07-21 20:20
Yes it's an issue duplicate of https://github.com/iam4x/pokemongo-webspoof/issues/62#issuecomment-234351434

**Closed by iam4x** 2016-07-21 20:20 UTC
