### ISSUE TITLE
Location Service Locked

### ISSUE THREAD

**Issue by fliipsyde** [iam4x/pokemongo-webspoof#161] opened 2016-07-22 01:52 UTC
Hi, I'm new to all of this xcode and github stuff, but I figured out how to get the program working.  The issue I wanted to bring up was that once I disconnected my phone from the system and closed the program, my location service was stuck where I parked my pokemon trainer.  I actually tested it with other apps as well when I had the issue, and my google maps location was also stuck at the location of my trainer.  Ultimately, I tried airplane mode, turning off and on location services and disabling location for the app and re-enabling it, closing and opening the app, etc.  but the only fix I found was to completely restart my phone.  I'm not sure if there was supposed to be a correct webspoof closing procedure to safely shut it down, or if this was just a bug, so I wanted to put it out here just so you know! 

Thanks for the awesome program! Cheers.

**Comment by adster93** [comment] 2016-07-22 02:55
Hey I am having the same issue, got kinda scared... just restarted my phone nad it works now

**Comment by adster93** [comment] 2016-07-22 03:02
think I actually got banned...

**Comment by fliipsyde** [comment] 2016-07-22 07:27
@adster93 Glad we both got it back up and working!  Definitely was a scare for me too.

**Comment by iam4x** [comment] 2016-07-22 07:28
Duplicate of #45

**Closed by iam4x** 2016-07-22 07:28 UTC
