### ISSUE TITLE
(suggestion) put pin as a destination

### ISSUE THREAD

**Issue by okynk** [iam4x/pokemongo-webspoof#65] opened 2016-07-20 04:10 UTC
i live in a rural area, i can't search any destination in my area
i think instead of search a destination, it would be much better if we can put a pin or some pins as destination/s

**Comment by wxrdn** [comment] 2016-07-20 07:03
yes this would be a very good feature to have, save us lots of time

**Comment by muescha** [comment] 2016-07-20 13:34
duplicate of #59

**Comment by iam4x** [comment] 2016-07-21 19:03
The feature is planned, need fixes before. Let's continue discussion into #59 👍

**Closed by iam4x** 2016-07-21 19:03 UTC
