### ISSUE TITLE
Use Pokévision API

### ISSUE THREAD

**Issue by bbbenja** [iam4x/pokemongo-webspoof#78] opened 2016-07-20 10:13 UTC
Use https://pokevision.com API to show live position of pokemon on the map

**Comment by AbelIngrand** [comment] 2016-07-20 10:29
They actually use the same API as https://github.com/AHAAAAAAA/PokemonGo-Map

**Comment by iam4x** [comment] 2016-07-21 19:33
Duplicate of #54

**Closed by iam4x** 2016-07-21 19:33 UTC
