### ISSUE TITLE
Blank screen

### ISSUE THREAD

**Issue by gere1234** [iam4x/pokemongo-webspoof#89] opened 2016-07-20 13:37 UTC
When i open the project, i change the bundle identifier then i start it on my ipad, but it give me a blank screen.

Can you help me ?

**Comment by muescha** [comment] 2016-07-20 13:39
duplicate of #74

**Comment by gere1234** [comment] 2016-07-20 16:55
oh sorry!

**Comment by iam4x** [comment] 2016-07-21 19:40
Fixed by @AbelIngrand will be in next release 👍

**Closed by iam4x** 2016-07-21 19:40 UTC
