### ISSUE TITLE
the application "pokemongo-webspoof" can't be opened

### ISSUE THREAD

**Issue by DerekCodeUp** [iam4x/pokemongo-webspoof#115] opened 2016-07-21 02:26 UTC
I cannot open the pokemongo-webspoof.app at all of version 110 and 103. However I can open the app of version 102. Please help!

**Comment by d3viant0ne** [comment] 2016-07-21 02:49
"I cannot open" isn't terribly helpful.

What operating system & what is the error it's throwing.

**Comment by Matador829** [comment] 2016-07-21 07:04
I'm having the same issue as well

I downloaded and set Pokemon Go to authorized.

When I click the app to open, it appear briefly on the Mac dock, but then shuts down automatically.  Xcode doesn't even load

**Comment by realphanta** [comment] 2016-07-21 07:57
Pull the app out of the archive to your desktop, start it from there. Might be a permissions problem. Was struggling with this too.

**Comment by CrazyJayson** [comment] 2016-07-21 11:38
Remove pokemongo-webspoof.app from authorized app to Accessibility
(System Preferences -> Security & Privacy -> Privacy Tab -> Accessibility)
Delete pokemongo-webspoof.app from your computer
Download latest release
Add back new pokemongo-webspoof.app to authorized app to Accessibility
(System Preferences -> Security & Privacy -> Privacy Tab -> Accessibility)

**Comment by DerekCodeUp** [comment] 2016-07-21 16:16
@CrazyJayson Thank you for your reply, but that cannot fix my issue.
The problem for me it's after I pulled out the app(pokemongo-webspoof.app) from archive(pokemongo-webspoof.app.tar.gz). Then I try to double click to open the app(pokemongo-webspoof), then mac system tell me "the application "pokemongo-webspoof" can't be opened". 
I think it's more likely a permisson issue. I'm using the most current Mac OS system. I know it's a little bizarre, could anyone help?

**Comment by iam4x** [comment] 2016-07-21 20:01
Duplicate of https://github.com/iam4x/pokemongo-webspoof/issues/74#issuecomment-234357780 please continue discussion there with your debug log.

**Closed by iam4x** 2016-07-21 20:01 UTC
