### ISSUE TITLE
Stopped working after PokemonGo update

### ISSUE THREAD

**Issue by m4ycee** [iam4x/pokemongo-webspoof#133] opened 2016-07-21 17:16 UTC
Unfortunately the app stopped working after last nights update to 1.0.3. Do you experience the same problem? The webspoof shows me somewhere in the ocean and I can't teleport anywhere. The location on the phone is correct.

**Comment by zhexuany** [comment] 2016-07-21 17:19
No. It still works. No matter how Pokemon Go update, this method should always works.

**Comment by d3viant0ne** [comment] 2016-07-21 17:23
I'm running on 1.0.3 just fine using a development build of master ( I had issues with the released version )

**Comment by LoganTheRed** [comment] 2016-07-21 17:24
I've been experiencing the same problem. Had it working smooth yesterday. But now I get a blank map and Error 2 on the app and my avatar on the Pokemon Go game doesn't go anywhere.

Running iOS 9.3.3 and the released version of the app.

**Comment by d3viant0ne** [comment] 2016-07-21 17:36
@LoganTheRed @m4ycee - My suggestion if you don't want to wait for the next tag would be to clone the repo and run it off the master branch. You will need NodeJS installed to do so ( i'm running 6.3.0 and it works fine )

If either of you don't have experience with node / have issues with the dev setup just comment here and i'll help get you going.

**Comment by zhexuany** [comment] 2016-07-21 17:39
@LoganTheRed @m4ycee  If it does't work. The problem is either you did not update correctly or you did not build the app correct.

**Comment by m4ycee** [comment] 2016-07-21 17:56
@d3viant0ne Thank you so much for taking the time to answer me. I would appreciate if you could link me to an instruction or quickly describe how I can do that.

**Comment by LoganTheRed** [comment] 2016-07-21 18:59
@zhexuany I built it the exact same way as yesterday, followed the readme precisely. Yesterday it worked fabulously. Then Pokemon Go updated itself to 1.03 and the same steps I went through yesterday result in the symptoms I described last night and today. Thought it was a temporary error until it continued today. So since the only thing that changed between working and non-working was the Pokemon GO app version, then what do you suggest I did wrong?

**Comment by d3viant0ne** [comment] 2016-07-21 19:06
@LoganTheRed - Suggest you completely remove everything from both your system and phone ( spoof app & trust relationship ) then go through the process fresh ( dev build suggested imo ).

**Comment by LoganTheRed** [comment] 2016-07-21 19:16
@d3viant0ne Yeah, I'm going to try and give that a try tonight. Should be interesting to see how badly I blow it up. I'm still fumbling my way around XCode :-D Thanks.

**Comment by iam4x** [comment] 2016-07-21 20:13
Try to remove everything, but seems more like an issue pokemongo app itself. I'll close this since it's not a bug with `pokemongo-webspoof` app 👍

**Closed by iam4x** 2016-07-21 20:13 UTC
