### ISSUE TITLE
Error autoclick Xcode - Code 2 (-1728)

### ISSUE THREAD

**Issue by Svena69** [iam4x/pokemongo-webspoof#28] opened 2016-07-18 04:02 UTC
Hi,

I've been using the app for 1 day now and all of a sudden i've got the following error in the location spoof app. The error goes as the following and pops up when I click "Auto update Xcode Location" and move.

"Error autoclick Xcode - Code 2"
"(file path) ../pokemongo-webspoof.app/Contents/Resources/app/autoclick.apple 
execution error: System Events got an error: Can't get menu item "pokemonLocation" of menu 1 of menu item "Simulate Location" of menu 1 of menu bar item "Debug" of menu bar 1 of process "Xcode". (-1728)

^Anyone know how to fix this?

**Comment by swizenfeld** [comment] 2016-07-18 05:13
u have to allow access to control ur computer on the control panel

**Comment by Svena69** [comment] 2016-07-18 07:31
> u have to allow access to control ur computer on the control panel

^ I've tried that already. Not sure if I'm doing something wrong but i've done the following already (multiple times):

I went to: System Preferences -> Security & Privacy -> Accessibility -> And I've added there the "pokemonggo-webspoof.app". (Here's a picture: https://gyazo.com/ba87a469a1a3e7c534199de51d870181)

Still no succes.

**Comment by iam4x** [comment] 2016-07-18 07:55
Focus Xcode and click by yourself once on Debug -> Simulate Location -> pokemonLocation it should work after.

**Comment by iam4x** [comment] 2016-07-18 07:55
duplicate of https://github.com/iam4x/pokemongo-webspoof/issues/5#issuecomment-233124626

**Closed by iam4x** 2016-07-18 07:55 UTC
Labels: question

**Comment by Svena69** [comment] 2016-07-18 08:01
> Focus Xcode and click by yourself once on Debug -> Simulate Location -> pokemonLocation it should work after.

^ I've also tried that multiple times without succes. However there's 2 things becoming clear now:

1. The pokemon go app does update the .gpx file when selecting "Auto Update Xcode location" because when I check the file in Xcode I see the coordinates change every time I move on the map. When selecting -> unselecting -> selecting the .gpx file from the debug menu (simulate location) this still doesn't fix it.

2. There's 2 errors when building (This didn't happen before when I was using the app yesterday and it worked fine):

- The provisioning profile "iOS Team Provisioning Profile: pokemongo1234" is expiring soon

- warning: skipping file '/var/folders/sc/f51fvfs17nv7wj3w1qkqxxyh0000gn/T/tmp-1334CLoe4hMm1A30/pokemonLocation.gpx' (unexpected file type 'text' in Frameworks & Libraries build phase)


^ I'm still trying to fix the problem.. Your help is really appreciated!

**Comment by iam4x** [comment] 2016-07-18 08:04
> The provisioning profile "iOS Team Provisioning Profile: pokemongo1234" is expiring soon

Try another name?

> warning: skipping file '/var/folders/sc/f51fvfs17nv7wj3w1qkqxxyh0000gn/T/tmp-1334CLoe4hMm1A30/pokemonLocation.gpx' (unexpected file type 'text' in Frameworks & Libraries build phase)

Just a warning should not block.

----

Do you still have an error in the pokemongo-webspoof.app?

**Comment by Svena69** [comment] 2016-07-18 08:07
> Do you still have an error in the pokemongo-webspoof.app?

Yes. When I start the "pokemongo-webspoof.app" from scratch and I click on "Auto Update Xcode location", without doing anything else, I get the error. (-1728)

> Try another name?

Done this, without succes / any changes.

**Comment by Svena69** [comment] 2016-07-18 08:17
Found something else interesting:

When I open the app normally -> directly open "pokemnongo-webspoof" I get the -1728 error in the app when trying to update location.

When I open the app in the following way: "pokemongo-webspoof" -> Show package contents -> Contents -> MacOS -> pokemongo-webspoof.exec I get the -1719 error, even though the app is added to my accessibility settings..

^ Still having the problem though.

**Comment by iam4x** [comment] 2016-07-18 08:20
1. Open the app normally
2. Build the Xcode project on your iOS device
3. Click auto-update Xcode location in the pokemongo-webspoof.app
4. Move a little -> It should throw -1728 error
5. Focus back Xcode, click yourself on Debug -> Simulate Location - pokemonLocation
6. Focus back pokenongo-webspoof.app and move, it should work as expected 👍

**Comment by Svena69** [comment] 2016-07-18 08:23
^ The following worked! Great work! Thanks for your time. I'm actually really confused that it works now.. haha! Cheers

**Comment by clockw1ze** [comment] 2016-07-18 16:13
Yep that worked! Thanks alot. New to this whole xcode/github stuff :D

**Comment by iam4x** [comment] 2016-07-19 18:41
Welcome @clockw1ze and enjoy your stay on github 💯

**Comment by StefanMeGit** [comment] 2016-07-24 14:34
Doesn't work for me... got always the the ERROR 
`ERROR AUTOCLICK XCODE 2 -1728`

Got the version 1.1.1 , fresh downloaded XCODE 7.3.1


:(
